[project]
name = "01-todo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.8",
]

[dependency-groups]
dev = [
    "ruff>=0.14.6",
]
